### ISSUE TITLE
Droptop 4.360.13 Breaks Dynamic Infos

### ISSUE THREAD

**Issue by yuuusername** [KazukiGames82/Dynamic_Infos-KazukiGames82#1]
Hi again!

After installing the new release of Droptop it seems that dynamic infos makes the left cluster have a white background and aligns the activity within this group:
![image](https://github.com/KazukiGames82/Dynamic_Infos-KazukiGames82/assets/72343301/70d621c7-7cf5-40dc-a564-8e0d73b3e6e3)
When I disable the app, it shows as expected:
![image](https://github.com/KazukiGames82/Dynamic_Infos-KazukiGames82/assets/72343301/08122692-13db-4241-af0e-9c4958b1f7c5)
and the activity is set to the centre. I've reset the app to default but it hasn't worked.

The only setting I've changed is the alignment: 
![image](https://github.com/KazukiGames82/Dynamic_Infos-KazukiGames82/assets/72343301/b6c5dd01-b199-494a-881d-6eb794dd21b1)

**Comment by KazukiGames82** [comment]
Carib made a mistake uploading an wrong version of Dynamic Infos, currently i'm aware about the white boxs in the top bar, i had a fixed version but if i upload now the website will still mark as there's a new update. 

Latest version from github looks like this, but has the white box issue.
![Rainmeter_wEGpjFki8f](https://github.com/KazukiGames82/Dynamic_Infos-KazukiGames82/assets/121910047/76d3f83f-f778-4534-99ed-241c4b204075)

**Comment by KazukiGames82** [comment]
@yuuusername New Update Released.
https://github.com/KazukiGames82/Dynamic_Infos-KazukiGames82/releases/tag/v24.0703
